import { useState, useEffect, useCallback } from 'react';
// Added icons for modals and fields
// Added missing Building icon
import { Plus, Trash2, Eye, Edit2, AlertTriangle, Building2, Shield, X, Hash, Calendar, FileText, User as IconUser, Info, AlignLeft, Power, Building } from 'lucide-react';
import { apiService, ApiError } from '../lib/api';
import { useAuth } from '../context/AuthContext';
// Import TipoAtividade from types, remove local definition
import type { TipoAtividade } from '../types';
import {
  PageLayout,
  PageHeader,
  SearchBar,
  IconButton,
  DataTable,
  ConfirmDialog,
  StatusBadge,
  StateHandler,
  ModalPadrao, // Import ModalPadrao
  type Column
} from '../components/ui';
// Removed local TipoAtividade interface definition

// Form Data Interface for Create/Edit Modal
interface TipoAtividadeFormData {
  nome: string;
  codigo?: string; // Código might be generated by backend on creation
  descricao: string;
  aplicavel_pf: boolean;
  aplicavel_pj: boolean;
  ativo: boolean;
}

export const TiposAtividadePage: React.FC = () => {
  const { user } = useAuth();
  const [tiposAtividade, setTiposAtividade] = useState<TipoAtividade[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [searchTerm, setSearchTerm] = useState('');
  const [tipoParaExcluir, setTipoParaExcluir] = useState<TipoAtividade | null>(null);

  // Modal States
  const [isModalCadastroOpen, setIsModalCadastroOpen] = useState(false);
  const [isModalVisualizacaoOpen, setIsModalVisualizacaoOpen] = useState(false);
  const [isModalEdicaoOpen, setIsModalEdicaoOpen] = useState(false);
  const [tipoParaVisualizar, setTipoParaVisualizar] = useState<TipoAtividade | null>(null);
  const [tipoParaEditar, setTipoParaEditar] = useState<TipoAtividade | null>(null);

  // Form State
   const [formData, setFormData] = useState<TipoAtividadeFormData>({
    nome: '',
    codigo: '', // Keep for edit, might clear for create
    descricao: '',
    aplicavel_pf: false,
    aplicavel_pj: false,
    ativo: true,
  });


  const isAdmin = Boolean(user?.gerente);

  const formatDate = (dateString?: string) => {
    if (!dateString) return '-';
    try {
        const date = new Date(dateString);
        const options: Intl.DateTimeFormatOptions = {
            day: '2-digit',
            month: '2-digit',
            year: 'numeric',
            hour: '2-digit',
            minute: '2-digit'
        };
        return new Intl.DateTimeFormat('pt-BR', options).format(date);
    } catch (e) {
        console.error("Error formatting date:", dateString, e);
        return '-';
    }
  };

  const fetchTiposAtividade = useCallback(async () => {
    // Only fetch if admin
    if (!isAdmin) {
      setLoading(false);
      setTiposAtividade([]);
      return;
    }

    try {
      setLoading(true);
      const params = searchTerm ? { search: searchTerm, ativo: true } : { ativo: true };
      const response = await apiService.getTiposAtividade(params);
      // Assuming response structure { data: [], ... } or []
      const data = response?.data ?? (Array.isArray(response) ? response : []);
      setTiposAtividade(data);
      setError('');
        } catch (error: unknown) { // Catch specific error type
            console.error('Erro ao buscar tipos de atividade:', error);
            const message = error instanceof Error && error.message ? error.message : 'Erro ao carregar tipos de atividade';
            setError(message);
      setTiposAtividade([]); // Clear data on error
    } finally {
      setLoading(false);
    }
  }, [searchTerm, isAdmin]); // Add isAdmin dependency

  useEffect(() => {
    fetchTiposAtividade();
  }, [fetchTiposAtividade]);

   const resetForm = () => {
        setFormData({
            nome: '',
            codigo: '',
            descricao: '',
            aplicavel_pf: false,
            aplicavel_pj: false,
            ativo: true,
        });
        setError(''); // Clear errors when resetting
   };

    // --- Modal Handlers ---
    const openModalCadastro = () => {
        resetForm();
        setIsModalCadastroOpen(true);
    };

    const openModalEdicao = (tipo: TipoAtividade) => {
        setFormData({
            nome: tipo.nome,
            codigo: tipo.codigo, // Display existing code
            descricao: tipo.descricao || '',
            aplicavel_pf: tipo.aplicavel_pf,
            aplicavel_pj: tipo.aplicavel_pj,
            ativo: tipo.ativo,
        });
        setTipoParaEditar(tipo);
        setIsModalEdicaoOpen(true);
        setError('');
    };

    const handleVisualizar = (tipo: TipoAtividade) => {
        setTipoParaVisualizar(tipo);
        setIsModalVisualizacaoOpen(true);
    };

    const handleFecharVisualizacao = () => {
        setIsModalVisualizacaoOpen(false);
        setTipoParaVisualizar(null);
    };

     const handleCloseCadastro = () => {
        setIsModalCadastroOpen(false);
        resetForm();
    };

    const handleCloseEdicao = () => {
        setIsModalEdicaoOpen(false);
        setTipoParaEditar(null);
        resetForm();
    };

    // --- CRUD Operations ---
    const handleSalvar = async (event?: React.FormEvent) => {
        event?.preventDefault(); // Prevent default form submission if used in a form
        if (!formData.nome.trim()) {
            setError("O nome é obrigatório.");
            return;
        }

        const nomeNormalizado = formData.nome.trim();
        const isEditing = Boolean(tipoParaEditar);

        const tipoExistenteMesmoNome = tiposAtividade.find((tipo) => {
            const nomeExistente = tipo.nome?.trim().toLowerCase();
            const candidato = nomeNormalizado.toLowerCase();
            const mesmoRegistro = isEditing && tipoParaEditar ? tipo.id === tipoParaEditar.id : false;
            return nomeExistente === candidato && !mesmoRegistro;
        });

        setLoading(true);
        setError('');

        try {
            const payloadBase = {
                nome: nomeNormalizado,
                descricao: formData.descricao?.trim() || '',
                aplicavel_pf: formData.aplicavel_pf,
                aplicavel_pj: formData.aplicavel_pj,
                ativo: formData.ativo,
            };

            if (!isEditing && tipoExistenteMesmoNome) {
                const codigoNormalizado = formData.codigo?.trim();
                const payloadReativacao = codigoNormalizado
                    ? { ...payloadBase, codigo: codigoNormalizado, ativo: true }
                    : { ...payloadBase, ativo: true };

                await apiService.updateTipoAtividade(tipoExistenteMesmoNome.id, payloadReativacao);
                fetchTiposAtividade();
                handleCloseCadastro();
                return;
            }

            if (isEditing && tipoParaEditar) {
                const codigoNormalizado = formData.codigo?.trim();
                const payloadAtualizacao = codigoNormalizado
                    ? { ...payloadBase, codigo: codigoNormalizado }
                    : payloadBase;

                await apiService.updateTipoAtividade(tipoParaEditar.id, payloadAtualizacao);
            } else {
                await apiService.createTipoAtividade(payloadBase);
            }

            fetchTiposAtividade(); // Refresh list
            if (isEditing) {
                handleCloseEdicao();
            } else {
                handleCloseCadastro();
            }

        } catch (err: unknown) {
            console.error(`Erro ao ${isEditing ? 'editar' : 'criar'} tipo de atividade:`, err);
            const message = err instanceof ApiError
                ? `Erro ${err.status}: ${JSON.stringify(err.details)}`
                : err instanceof Error
                ? err.message
                : 'Erro desconhecido';
            setError(`Falha ao salvar: ${message}`);
        } finally {
            setLoading(false);
        }
    };


    const handleExcluir = async () => {
        if (!tipoParaExcluir) return;

        try {
        setLoading(true); // Indicate loading during delete
    await apiService.deleteTipoAtividade(tipoParaExcluir.id);
    setTiposAtividade(prev => prev.filter(t => t.id !== tipoParaExcluir.id));
    setTipoParaExcluir(null);
    setError(''); // Clear error on success
    } catch (error: unknown) { // Catch specific error type
    console.error('Erro ao excluir tipo de atividade:', error);
    const message = error instanceof Error && error.message ? error.message : 'Erro ao excluir tipo de atividade';
    setError(message);
        } finally {
        setLoading(false);
        }
    };

    const handleInputChange = (field: keyof TipoAtividadeFormData, value: string | boolean) => {
        setFormData(prev => ({ ...prev, [field]: value }));
        if (error) setError(''); // Clear error on input change
    };


    const columns: Column<TipoAtividade>[] = [
        {
            key: 'nome',
            label: 'Nome',
            render: (_, item) => (
                <div className="flex items-center">
                    <div className="w-8 h-8 bg-indigo-50 rounded-full flex items-center justify-center mr-3 flex-shrink-0">
                        <Building2 className="w-4 h-4 text-indigo-600" />
                    </div>
                    <div>
                        <div className="text-sm font-medium text-gray-900">{item.nome}</div>
                        <div className="text-sm text-gray-500">ID: {item.id}</div>
                    </div>
                </div>
            )
        },
        {
            key: 'codigo', // Changed key to 'codigo' if it exists in the type
            label: 'Código',
            render: (_, item) => ( // Render based on item
                <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-blue-50 text-blue-800 font-mono">
                    {item.codigo || 'N/A'}
                </span>
            )
        },
        {
            key: 'aplicavel_pf', // Use existing field as key for aplicabilidade column
            label: 'Aplicabilidade',
            render: (_, item) => (
                <div className="flex flex-col space-y-1 items-start">
                    {item.aplicavel_pf && (
                        <span className="inline-flex items-center px-2 py-0.5 rounded text-xs font-medium bg-blue-100 text-blue-800">PF</span>
                    )}
                    {item.aplicavel_pj && (
                        <span className="inline-flex items-center px-2 py-0.5 rounded text-xs font-medium bg-green-100 text-green-800">PJ</span>
                    )}
                </div>
            )
        },
        {
            key: 'ativo',
            label: 'Status',
            render: (_, item) => (
                <StatusBadge status={item.ativo ? 'ativo' : 'inativo'} />
            )
        },
        {
            key: 'created_at',
            label: 'Criado em',
            render: (_, item) => (
                <span className="text-sm text-gray-500">
                    {item.created_at && typeof item.created_at === 'string'
                    ? new Date(item.created_at).toLocaleDateString('pt-BR')
                    : '-'}
                </span>
            )
        }
    ];

  if (!isAdmin && !loading) { // Check loading state here too
    return (
      <PageLayout>
         <PageHeader
            title="Tipos de Atividade"
            subtitle="Configure os tipos de atividade contábil disponíveis"
          />
        <div className="flex items-center justify-center min-h-[400px] bg-white rounded-lg shadow-sm border border-red-200 p-8">
          <div className="text-center">
            <AlertTriangle className="mx-auto h-12 w-12 text-red-500 mb-4" />
            <h2 className="text-xl font-semibold text-gray-900 mb-2">Acesso Negado</h2>
            <p className="text-gray-600">Você não tem permissão para acessar esta página.</p>
          </div>
        </div>
      </PageLayout>
    );
  }

  return (
    <PageLayout>
      <PageHeader
        title="Tipos de Atividade"
        subtitle="Configure os tipos de atividade contábil disponíveis"
      >
       {isAdmin && ( // Show button only if admin
          <IconButton
            icon={Plus}
            label="Novo Tipo"
            onClick={openModalCadastro} // Open the creation modal
            variant="primary"
          />
       )}
      </PageHeader>

      <SearchBar
        value={searchTerm}
        onChange={setSearchTerm}
        placeholder="Buscar tipos de atividade..."
        className="mb-6"
      />

        <StateHandler
            loading={loading}
            error={error}
            onErrorDismiss={() => setError('')}
            isEmpty={tiposAtividade.length === 0 && !loading} // Only show empty if not loading
            emptyState={
                <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-8 text-center">
                    <Building2 className="mx-auto h-12 w-12 text-gray-400 mb-4" /> {/* Changed icon */}
                    <p className="text-gray-500">
                        {searchTerm
                         ? `Nenhum tipo de atividade encontrado para "${searchTerm}"`
                         : "Nenhum tipo de atividade encontrado."}
                    </p>
                     {isAdmin && !searchTerm && ( // Show button only if admin and not searching
                        <button
                            onClick={openModalCadastro} // Open the creation modal
                            className="mt-4 text-sm text-blue-600 hover:text-blue-800 font-medium"
                        >
                            + Cadastrar Novo Tipo
                        </button>
                    )}
                </div>
            }
        >
        <DataTable
            data={tiposAtividade}
            columns={columns}
            actions={(item) => (
                 <div className="flex items-center justify-end space-x-1"> {/* Align actions */}
                    <IconButton
                        icon={Eye}
                        onClick={() => handleVisualizar(item)} // Open view modal
                        variant="outline"
                        size="sm"
                        title="Visualizar"
                    />
                   {isAdmin && ( // Show edit/delete only if admin
                    <>
                        <IconButton
                            icon={Edit2}
                            onClick={() => openModalEdicao(item)} // Open edit modal
                            variant="outline"
                            size="sm"
                            title="Editar"
                        />
                        <IconButton
                            icon={Trash2}
                            onClick={() => setTipoParaExcluir(item)}
                            variant="danger"
                            size="sm"
                            title="Excluir"
                        />
                    </>
                   )}
                </div>
            )}
            />
        </StateHandler>

        {/* --- MODALS --- */}

        {/* Modal de Cadastro */}
        <ModalPadrao
            isOpen={isModalCadastroOpen}
            onClose={handleCloseCadastro}
            title="Cadastrar Novo Tipo de Atividade"
            confirmLabel={loading ? 'Salvando...' : 'Cadastrar'}
            onConfirm={handleSalvar}
            size="lg"
            showFooter={true}
        >
            <form onSubmit={handleSalvar} className="space-y-4">
                 {error && (
                    <div className="bg-red-50 border border-red-200 text-red-700 px-4 py-2 rounded text-sm flex items-start space-x-2" role="alert">
                        <AlertTriangle className="w-5 h-5 flex-shrink-0 text-red-400" />
                        <span>{error}</span>
                    </div>
                )}
                 <div>
                    <label htmlFor="tipo-nome-cad" className="flex items-center text-sm font-medium text-gray-700 mb-1">
                         <Building2 className="w-4 h-4 mr-2 text-gray-400"/> Nome *
                    </label>
                    <input
                        id="tipo-nome-cad"
                        type="text"
                        value={formData.nome}
                        onChange={(e) => handleInputChange('nome', e.target.value)}
                        className={`w-full px-3 py-2 border rounded-lg focus:ring-2 focus:border-transparent text-sm transition-colors ${error && !formData.nome.trim() ? 'border-red-500 focus:ring-red-500' : 'border-gray-300 focus:ring-blue-500'}`}
                        required
                        disabled={loading}
                    />
                 </div>
                 {/* Descrição */}
                <div>
                    <label htmlFor="tipo-descricao-cad" className="flex items-center text-sm font-medium text-gray-700 mb-1">
                        <AlignLeft className="w-4 h-4 mr-2 text-gray-400" /> Descrição (Opcional)
                    </label>
                    <textarea
                        id="tipo-descricao-cad"
                        value={formData.descricao}
                        onChange={(e) => handleInputChange('descricao', e.target.value)}
                        rows={3}
                        className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent text-sm transition-colors"
                        disabled={loading}
                    />
                </div>
                {/* Aplicabilidade */}
                <fieldset className="space-y-3 pt-2">
                    <legend className="block text-sm font-medium text-gray-700 mb-2">
                        Aplicabilidade
                    </legend>
                    <div className="flex items-center space-x-6">
                        <div className="flex items-center">
                        <input
                            type="checkbox"
                            id="aplicavel_pf_cad"
                            checked={formData.aplicavel_pf}
                            onChange={(e) => handleInputChange('aplicavel_pf', e.target.checked)}
                            className="w-4 h-4 text-blue-600 border-gray-300 rounded focus:ring-blue-500"
                            disabled={loading}
                        />
                        <label htmlFor="aplicavel_pf_cad" className="ml-2 text-sm text-gray-700 flex items-center cursor-pointer">
                            <IconUser className="w-4 h-4 mr-1.5 text-blue-500" /> Pessoa Física
                        </label>
                        </div>
                        <div className="flex items-center">
                        <input
                            type="checkbox"
                            id="aplicavel_pj_cad"
                            checked={formData.aplicavel_pj}
                            onChange={(e) => handleInputChange('aplicavel_pj', e.target.checked)}
                            className="w-4 h-4 text-green-600 border-gray-300 rounded focus:ring-green-500"
                            disabled={loading}
                        />
                        <label htmlFor="aplicavel_pj_cad" className="ml-2 text-sm text-gray-700 flex items-center cursor-pointer">
                            <Building className="w-4 h-4 mr-1.5 text-green-500" /> Pessoa Jurídica
                        </label>
                        </div>
                    </div>
                </fieldset>
                 {/* Ativo (usually default true for creation) */}
                <div className="flex items-center pt-2">
                    <input
                        type="checkbox"
                        id="ativo_cad"
                        checked={formData.ativo}
                        onChange={(e) => handleInputChange('ativo', e.target.checked)}
                        className="w-4 h-4 text-blue-600 border-gray-300 rounded focus:ring-blue-500"
                        disabled={loading}
                    />
                    <label htmlFor="ativo_cad" className="ml-2 text-sm text-gray-700 flex items-center cursor-pointer">
                        <Power className="w-4 h-4 mr-1.5 text-gray-400" /> Manter Ativo
                    </label>
                </div>
                {/* Submit button is handled by ModalPadrao footer */}
            </form>
        </ModalPadrao>

        {/* Modal de Edição */}
        <ModalPadrao
            isOpen={isModalEdicaoOpen}
            onClose={handleCloseEdicao}
            title="Editar Tipo de Atividade"
            confirmLabel={loading ? 'Salvando...' : 'Salvar Alterações'}
            onConfirm={handleSalvar}
            size="lg"
            showFooter={true}
        >
            <form onSubmit={handleSalvar} className="space-y-4">
                 {error && (
                    <div className="bg-red-50 border border-red-200 text-red-700 px-4 py-2 rounded text-sm flex items-start space-x-2" role="alert">
                        <AlertTriangle className="w-5 h-5 flex-shrink-0 text-red-400" />
                        <span>{error}</span>
                    </div>
                )}
                 <div>
                    <label className="flex items-center text-sm font-medium text-gray-700 mb-1">
                         <Hash className="w-4 h-4 mr-2 text-gray-400"/> Código (Gerado automaticamente)
                    </label>
                     <p className="text-sm text-gray-900 bg-gray-100 p-2 rounded">{formData.codigo || 'N/A'}</p>
                 </div>
                 <div>
                    <label htmlFor="tipo-nome-edit" className="flex items-center text-sm font-medium text-gray-700 mb-1">
                         <Building2 className="w-4 h-4 mr-2 text-gray-400"/> Nome *
                    </label>
                    <input
                        id="tipo-nome-edit"
                        type="text"
                        value={formData.nome}
                        onChange={(e) => handleInputChange('nome', e.target.value)}
                        className={`w-full px-3 py-2 border rounded-lg focus:ring-2 focus:border-transparent text-sm transition-colors ${error && !formData.nome.trim() ? 'border-red-500 focus:ring-red-500' : 'border-gray-300 focus:ring-blue-500'}`}
                        required
                        disabled={loading}
                    />
                 </div>
                 {/* Descrição */}
                <div>
                    <label htmlFor="tipo-descricao-edit" className="flex items-center text-sm font-medium text-gray-700 mb-1">
                        <AlignLeft className="w-4 h-4 mr-2 text-gray-400" /> Descrição (Opcional)
                    </label>
                    <textarea
                        id="tipo-descricao-edit"
                        value={formData.descricao}
                        onChange={(e) => handleInputChange('descricao', e.target.value)}
                        rows={3}
                        className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent text-sm transition-colors"
                        disabled={loading}
                    />
                </div>
                 {/* Aplicabilidade */}
                <fieldset className="space-y-3 pt-2">
                    <legend className="block text-sm font-medium text-gray-700 mb-2">
                        Aplicabilidade
                    </legend>
                    <div className="flex items-center space-x-6">
                        <div className="flex items-center">
                        <input
                            type="checkbox"
                            id="aplicavel_pf_edit"
                            checked={formData.aplicavel_pf}
                            onChange={(e) => handleInputChange('aplicavel_pf', e.target.checked)}
                            className="w-4 h-4 text-blue-600 border-gray-300 rounded focus:ring-blue-500"
                            disabled={loading}
                        />
                        <label htmlFor="aplicavel_pf_edit" className="ml-2 text-sm text-gray-700 flex items-center cursor-pointer">
                            <IconUser className="w-4 h-4 mr-1.5 text-blue-500" /> Pessoa Física
                        </label>
                        </div>
                        <div className="flex items-center">
                        <input
                            type="checkbox"
                            id="aplicavel_pj_edit"
                            checked={formData.aplicavel_pj}
                            onChange={(e) => handleInputChange('aplicavel_pj', e.target.checked)}
                            className="w-4 h-4 text-green-600 border-gray-300 rounded focus:ring-green-500"
                            disabled={loading}
                        />
                        <label htmlFor="aplicavel_pj_edit" className="ml-2 text-sm text-gray-700 flex items-center cursor-pointer">
                            <Building className="w-4 h-4 mr-1.5 text-green-500" /> Pessoa Jurídica
                        </label>
                        </div>
                    </div>
                </fieldset>
                 {/* Ativo */}
                <div className="flex items-center pt-2">
                    <input
                        type="checkbox"
                        id="ativo_edit"
                        checked={formData.ativo}
                        onChange={(e) => handleInputChange('ativo', e.target.checked)}
                        className="w-4 h-4 text-blue-600 border-gray-300 rounded focus:ring-blue-500"
                        disabled={loading}
                    />
                    <label htmlFor="ativo_edit" className="ml-2 text-sm text-gray-700 flex items-center cursor-pointer">
                        <Power className="w-4 h-4 mr-1.5 text-gray-400" /> Manter Ativo
                    </label>
                </div>
                 {/* Submit button is handled by ModalPadrao footer */}
            </form>
        </ModalPadrao>

        {/* Modal de Visualização */}
        <ModalPadrao
            isOpen={isModalVisualizacaoOpen}
            onClose={handleFecharVisualizacao}
            title="Detalhes do Tipo de Atividade"
            showFooter={true}
            confirmLabel="Fechar"
            onConfirm={handleFecharVisualizacao}
            size="lg"
            >
             {tipoParaVisualizar && (
                <div className="space-y-6">
                    {/* Identificação Section */}
                    <div className="p-4 bg-gray-50 rounded-lg border border-gray-200">
                        <div className="flex items-center mb-3">
                            <Info className="w-5 h-5 text-blue-600 mr-2" />
                            <h3 className="text-lg font-semibold text-gray-800">Identificação</h3>
                        </div>
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-x-6 gap-y-4 text-sm">
                            <div>
                                <label className="flex items-center text-xs font-medium text-gray-500 mb-1"><Hash className="w-3 h-3 mr-1" /> Código</label>
                                <p className="text-gray-900 font-mono bg-gray-100 px-2 py-1 rounded w-fit">{tipoParaVisualizar.codigo}</p>
                            </div>
                            <div>
                                <label className="block text-xs font-medium text-gray-500 mb-1">Nome</label>
                                <p className="text-gray-900 font-semibold">{tipoParaVisualizar.nome}</p>
                            </div>
                             <div>
                                <label className="block text-xs font-medium text-gray-500 mb-1">Status</label>
                                <StatusBadge status={tipoParaVisualizar.ativo ? 'ativo' : 'inativo'} />
                            </div>
                        </div>
                    </div>

                    {/* Aplicabilidade Section */}
                    <div className="p-4 bg-gray-50 rounded-lg border border-gray-200">
                        <div className="flex items-center mb-3">
                            <Building2 className="w-5 h-5 text-emerald-600 mr-2" />
                            <h3 className="text-lg font-semibold text-gray-800">Aplicabilidade</h3>
                        </div>
                         <div className="grid grid-cols-1 md:grid-cols-2 gap-x-6 gap-y-4 text-sm">
                           <div>
                                <label className="flex items-center text-xs font-medium text-gray-500 mb-1"><IconUser className="w-3 h-3 mr-1" /> Pessoa Física</label>
                                <p className={`text-gray-900 ${tipoParaVisualizar.aplicavel_pf ? 'font-medium text-green-700' : 'italic text-gray-500'}`}>{tipoParaVisualizar.aplicavel_pf ? 'Sim' : 'Não'}</p>
                            </div>
                            <div>
                                <label className="flex items-center text-xs font-medium text-gray-500 mb-1"><Building className="w-3 h-3 mr-1" /> Pessoa Jurídica</label>
                                <p className={`text-gray-900 ${tipoParaVisualizar.aplicavel_pj ? 'font-medium text-green-700' : 'italic text-gray-500'}`}>{tipoParaVisualizar.aplicavel_pj ? 'Sim' : 'Não'}</p>
                            </div>
                        </div>
                    </div>

                    {/* Descrição Section */}
                    {tipoParaVisualizar.descricao && (
                        <div className="p-4 bg-gray-50 rounded-lg border border-gray-200">
                            <div className="flex items-center mb-3"><AlignLeft className="w-5 h-5 text-gray-600 mr-2" /><h3 className="text-lg font-semibold text-gray-800">Descrição</h3></div>
                            <p className="text-sm text-gray-700 whitespace-pre-wrap">{tipoParaVisualizar.descricao}</p>
                        </div>
                    )}

                     {/* Datas Section */}
                    <div className="p-4 bg-gray-50 rounded-lg border border-gray-200">
                        <div className="flex items-center mb-3"><Calendar className="w-5 h-5 text-purple-600 mr-2" /><h3 className="text-lg font-semibold text-gray-800">Datas</h3></div>
                         <div className="grid grid-cols-1 md:grid-cols-2 gap-x-6 gap-y-4 text-sm">
                            <div>
                                <label className="block text-xs font-medium text-gray-500 mb-1">Data de Criação</label>
                                <p className="text-gray-900">{formatDate(tipoParaVisualizar.created_at)}</p>
                            </div>
                             <div>
                                <label className="block text-xs font-medium text-gray-500 mb-1">Última Atualização</label>
                                <p className="text-gray-900">{formatDate(tipoParaVisualizar.updated_at)}</p>
                            </div>
                        </div>
                    </div>
                </div>
            )}
        </ModalPadrao>

        <ConfirmDialog
            open={!!tipoParaExcluir}
            title="Confirmar Exclusão"
            message={`Tem certeza que deseja excluir o tipo de atividade "${tipoParaExcluir?.nome}"? Esta ação marcará o tipo como inativo.`}
            onConfirm={handleExcluir}
            onCancel={() => setTipoParaExcluir(null)}
            confirmLabel="Sim, excluir"
            cancelLabel="Cancelar"
            variant="danger" // Use danger variant for delete confirmation
        />
        </PageLayout>
    );
};

